language: node_js
node_js:
- '8'
install:
- yarn global add node-gyp
- yarn global add gulp-cli
- yarn
cache:
  directories:
  - node_modules
  - $(npm config get prefix)/bin/gulp-cli
script: gulp build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
