language: node_js
node_js:
- '11'
install:
- npm i -g node-gyp
- npm i -g gulp
- npm i
script: gulp build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist
